language: node_js
node_js:
  - "14.16.1"

cache: yarn

branches:
  only:
    - master

matrix:
  include:
    - name: "borrow-ui/ui"
      env: PACKAGE_LOCATION=packages/ui

script:
  - cd $PACKAGE_LOCATION
  - yarn coveralls
